name: Update Daily Message

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README
        run: |
          messages=("Message 1" "Message 2" "Message 3")
          random_message="${messages[RANDOM % ${#messages[@]}]}"
          sed -i "s/<!--START_SECTION:message-of-the-day-->.*<!--END_SECTION:message-of-the-day-->/<!--START_SECTION:message-of-the-day-->\n> Today's message: $random_message\n<!--END_SECTION:message-of-the-day-->/" README.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update daily message"
          git push
        env:
          RANDOM: ${{ job.services.random.integers }}
        working-directory: ./
      
